#!/usr/bin/env python
configfile: "config.yaml"

rule all:
    input:
        expand("sorted_reads/{sample}.bam", sample=config["samples"])

rule hisat_map:
    input:
        left = config["readDir"]+"/{sample}_1.fastq",
        right = config["readDir"]+"/{sample}_2.fastq"
    output:
        "mapped_reads/{sample}.bam"
    threads:
        4
    params:
        indx = config["index"]
    log:
        "logs/hisat2/{sample}.log"
    shell:
        "(hisat2 -p {threads} -q -x {params.indx} -1 {input.left} -2 {input.right} | "
        "samtools view -Sb - > {output}) 2> {log}"

rule samtools_sort:
    input:
        "mapped_reads/{sample}.bam"
    output:
        "sorted_reads/{sample}.bam"
    threads:
        1
    params:
        m="12G"
    shell:
        "samtools sort -m {params.m} -T sorted_reads/{wildcards.sample} "
        "-O bam {input} > {output}"

