#!/usr/bin/env python
configfile: "config.yaml"

rule hisat_map:
    input:
        indx = config["index"]
        left = "{sample}_1.fastq",
        right = "{sample}_2.fastq"
    output:
        "mapped_reads/{sample}.bam"


