#!/usr/bin/env python
#configfile: "config.yaml"
read_path = config["readPath"]


rule velvet:
    input:
        "velvet_{sample}"

rule velveth:
    input:
        left=read_path + "{sample}_1.fastq",
        right=read_path + "{sample}_2.fastq"
    output:
        "velvet_{sample}"
    params:
        k=23,
        read="-shortPaired",
        type="-fastq"
    threads: 1    
    shell:
        "velveth {output} {params.k} {params.type} {params.read} {input.left} {input.right}"

rule velvetg:
    input:
        "velvet_{sample}"
    output:
        "velvet_{sample}/contigs.fa"
    params:
        cutoff = 4
    threads: 1

    shell:
        "velvetg {input} -cov_cutoff {params.cutoff}"
